/// @description Add 10 to
with(obj_custommode_cntrl){
var par=obj_smodeParent;
#region//Comet
	#region//Base
	if(room==rm_editcomet_armorCM){
		if(comet_armor=="constant"){
			if(comet_constant_armor<par.max_hp-(par.dif_hpPP-1))comet_constant_armor+=par.dif_hpPP;
		}
	}
	if(room==rm_editcomet_dmgCM){
		if(comet_dmg=="constant"){
			if(comet_constant_dmg<par.max_dmg-(par.dif_dmgPP-1))comet_constant_dmg+=par.dif_dmgPP;
		}
	}
	#endregion
	#region//Death
	if(room==rm_editcomet_pointsCM){
		if(comet_points=="constant"){
			if(comet_constant_points<par.max_points-(par.dif_pointsPP-1))comet_constant_points+=par.dif_pointsPP;
		}
	}
	#endregion
#endregion
#region//Bat
	#region//Base
	if(room==rm_editbat_armorCM){
		if(bat_armor=="constant"){
			if(bat_constant_armor<par.max_hp-(par.dif_hpPP-1))bat_constant_armor+=par.dif_hpPP;
		}
	}
	if(room==rm_editbat_dmgCM){
		if(bat_dmg=="constant"){
			if(bat_constant_dmg<par.max_dmg-(par.dif_dmgPP-1))bat_constant_dmg+=par.dif_dmgPP;
		}
	}
	#endregion
	#region//Death
	if(room==rm_editbat_pointsCM){
		if(bat_points=="constant"){
			if(bat_constant_points<par.max_points-(par.dif_pointsPP-1))bat_constant_points+=par.dif_pointsPP;
		}
	}
	#endregion
#endregion
#region//En Ship1
	#region//Base
	if(room==rm_edit_enShip1_armorCM){
		if(en_ship1_armor=="constant"){
			if(en_ship1_constant_armor<par.max_hp-(par.dif_hpPP-1))en_ship1_constant_armor+=par.dif_hpPP;
		}
	}
	/*if(room==rm_edit_enShip1_dmgCM){
		if(en_ship1_dmg=="constant"){
			if(en_ship1_constant_dmg<par.max_dmg-(par.dif_dmgPP-1))en_ship1_constant_dmg+=par.dif_dmgPP;
		}
	}*/
	#endregion
	#region//Death
	if(room==rm_edit_enShip1_pointsCM){
		if(en_ship1_points=="constant"){
			if(en_ship1_constant_points<par.max_points-(par.dif_pointsPP-1))en_ship1_constant_points+=par.dif_pointsPP;
		}
	}
	#endregion
#endregion
#region//HLaser
	#region//Base
	if(room==rm_edit_HLaser_dmgCM){
		if(hlaser_dmg=="constant"){
			if(hlaser_constant_dmg<par.max_dmg-(par.dif_dmgPP-1))hlaser_constant_dmg+=par.dif_dmgPP;
		}
	}
	#endregion
#endregion
}