/// @description  player_minigun_state
var mlaser;
shoot_button = mouse_check_button(mb_left) or keyboard_check(vk_space) or gamepad_button_check(oGamepad, gp_shoulderrb) or gamepad_button_check(oGamepad, gp_face1);
if (global.shooting == "auto") {
    mlaser = instance_create(x+12, y-8, obj_minilaser);
    mlaser = instance_create(x-16, y-8, obj_minilaser);
    mlaser = instance_create(x+11, y-8, obj_minilaser);
    mlaser = instance_create(x-11, y-8, obj_minilaser);
    mlaser = instance_create(x+13, y-8, obj_minilaser);
	audio_play_sound(snd_minilaser, 3, false);
	player_flares(0,0);
    mlaser = instance_create(x-13, y-8, obj_minilaser);
    mlaser = instance_create(x+14, y-8, obj_minilaser);
    mlaser = instance_create(x-14, y-8, obj_minilaser);
    mlaser = instance_create(x+15, y-8, obj_minilaser);
    mlaser = instance_create(x-15, y-8, obj_minilaser);
    mlaser = instance_create(x+12, y-8, obj_minilaser);
    mlaser = instance_create(x-14, y-8, obj_minilaser);
    mlaser = instance_create(x-16, y-8, obj_minilaser);
    mlaser = instance_create(x+11, y-8, obj_minilaser);
    mlaser = instance_create(x-11, y-8, obj_minilaser);
	audio_play_sound(snd_minilaser, 3, false);
    mlaser = instance_create(x+13, y-8, obj_minilaser);
    mlaser = instance_create(x-13, y-8, obj_minilaser);
    mlaser = instance_create(x+14, y-8, obj_minilaser);
    mlaser = instance_create(x-14, y-8, obj_minilaser);
    mlaser = instance_create(x+15, y-8, obj_minilaser);
    mlaser = instance_create(x-15, y-8, obj_minilaser);
    mlaser = instance_create(x+12, y-8, obj_minilaser);
	audio_play_sound(snd_minilaser, 3, false);
	player_flares(0,0);
    mlaser = instance_create(x-14, y-8, obj_minilaser);
    mlaser = instance_create(x+14, y-8, obj_minilaser);
    mlaser = instance_create(x-11, y-8, obj_minilaser);
    mlaser = instance_create(x+13, y-8, obj_minilaser);
    mlaser = instance_create(x-13, y-8, obj_minilaser);
    mlaser = instance_create(x+11, y-8, obj_minilaser);
    mlaser = instance_create(x-14, y-8, obj_minilaser);
    mlaser = instance_create(x+15, y-8, obj_minilaser);
    mlaser = instance_create(x-16, y-8, obj_minilaser);
	audio_play_sound(snd_minilaser, 3, false);
} else if (global.shooting == "manual" and shoot_button) {
    mlaser = instance_create(x+12, y-8, obj_minilaser);
    mlaser = instance_create(x-16, y-8, obj_minilaser);
    mlaser = instance_create(x+11, y-8, obj_minilaser);
    mlaser = instance_create(x-11, y-8, obj_minilaser);
    mlaser = instance_create(x+13, y-8, obj_minilaser);
	audio_play_sound(snd_minilaser, 3, false);
	player_flares(0,0);
    mlaser = instance_create(x-13, y-8, obj_minilaser);
    mlaser = instance_create(x+14, y-8, obj_minilaser);
    mlaser = instance_create(x-14, y-8, obj_minilaser);
    mlaser = instance_create(x+15, y-8, obj_minilaser);
    mlaser = instance_create(x-15, y-8, obj_minilaser);
    mlaser = instance_create(x+12, y-8, obj_minilaser);
    mlaser = instance_create(x-14, y-8, obj_minilaser);
    mlaser = instance_create(x-16, y-8, obj_minilaser);
    mlaser = instance_create(x+11, y-8, obj_minilaser);
    mlaser = instance_create(x-11, y-8, obj_minilaser);
	audio_play_sound(snd_minilaser, 3, false);
    mlaser = instance_create(x+13, y-8, obj_minilaser);
    mlaser = instance_create(x-13, y-8, obj_minilaser);
    mlaser = instance_create(x+14, y-8, obj_minilaser);
    mlaser = instance_create(x-14, y-8, obj_minilaser);
    mlaser = instance_create(x+15, y-8, obj_minilaser);
    mlaser = instance_create(x-15, y-8, obj_minilaser);
    mlaser = instance_create(x+12, y-8, obj_minilaser);
	audio_play_sound(snd_minilaser, 3, false);
	player_flares(0,0);
    mlaser = instance_create(x-14, y-8, obj_minilaser);
    mlaser = instance_create(x+14, y-8, obj_minilaser);
    mlaser = instance_create(x-11, y-8, obj_minilaser);
    mlaser = instance_create(x+13, y-8, obj_minilaser);
    mlaser = instance_create(x-13, y-8, obj_minilaser);
    mlaser = instance_create(x+11, y-8, obj_minilaser);
    mlaser = instance_create(x-14, y-8, obj_minilaser);
    mlaser = instance_create(x+15, y-8, obj_minilaser);
    mlaser = instance_create(x-16, y-8, obj_minilaser);
	audio_play_sound(snd_minilaser, 3, false);
}

with(obj_sword) instance_destroy();