/// @description Set to maximum
with(obj_custommode_cntrl){
var par=obj_smodeParent;
#region//Comet
	#region//Base
		if(room==rm_editcomet_armorCM){
			if(comet_armor=="random")if(comet_startR_armor<comet_endR_armor-par.dif_hp)comet_startR_armor+=par.dif_hp;
		}
		if(room==rm_editcomet_speedCM){
			if(comet_speed=="random")if(comet_startR_speed<comet_endR_speed-par.dif_speed)comet_startR_speed+=par.dif_speed;
		}
		if(room==rm_editcomet_dmgCM){
			if(comet_dmg=="random")if(comet_startR_dmg<comet_endR_dmg-par.dif_dmg)comet_startR_dmg+=par.dif_dmg;
		}
	#endregion
	#region//Death
		if(room==rm_editcomet_pointsCM){
			if(comet_points=="random"){
				if(comet_startR_points<comet_endR_points-par.dif_points)comet_startR_points+=par.dif_points;
			}
		}
	#endregion
	#region//Appearance
		if(room==rm_editcomet_sizeCM){
			if(comet_size=="random")if(comet_startR_size<comet_endR_size-par.dif_size)comet_startR_size+=par.dif_size;
		}
	#endregion
#endregion
#region//Bat
	#region//Base
		if(room==rm_editbat_armorCM){
			if(bat_armor=="random")if(bat_startR_armor<bat_endR_armor-par.dif_hp)bat_startR_armor+=par.dif_hp;
		}
		if(room==rm_editbat_speedCM){
			if(bat_speed=="random")if(bat_startR_speed<bat_endR_speed-par.dif_speed)bat_startR_speed+=par.dif_speed;
		}
		if(room==rm_editbat_dmgCM){
			if(bat_dmg=="random")if(bat_startR_dmg<bat_endR_dmg-par.dif_dmg)bat_startR_dmg+=par.dif_dmg;
		}
	#endregion
	#region//Death
		if(room==rm_editbat_pointsCM){
			if(bat_points=="random"){
				if(bat_startR_points<bat_endR_points-par.dif_points)bat_startR_points+=par.dif_points;
			}
		}
	#endregion
	#region//Appearance
		if(room==rm_editbat_sizeCM){
			if(bat_size=="random")if(bat_startR_size<bat_endR_size-par.dif_size)bat_startR_size+=par.dif_size;
		}
	#endregion
	#region//Bullet
		if(room==rm_editbat_bt_freqCM){
			if(bat_bt_freq=="random")if(bat_bt_startR_freq<bat_bt_endR_freq-par.dif_freq)bat_bt_startR_freq+=par.dif_freq;
		}
		if(room==rm_editbat_bt_speedCM){
			if(bat_bt_speed=="random")if(bat_bt_startR_speed<bat_bt_endR_speed-par.dif_speed)bat_bt_startR_speed+=par.dif_speed;
		}
		if(room==rm_editbat_bt_dmgCM){
			if(bat_bt_dmg=="random")if(bat_bt_startR_dmg<bat_bt_endR_dmg-par.dif_dmg)bat_bt_startR_dmg+=par.dif_dmg;
		}
		if(room==rm_editbat_bt_sizeCM){
			if(bat_bt_size=="random")if(bat_bt_startR_size<bat_bt_endR_size-par.dif_size)bat_bt_startR_size+=par.dif_size;
		}
	#endregion
#endregion
#region//Enemy Ship1
	#region//Base
		if(room==rm_edit_enShip1_armorCM){
			if(en_ship1_armor=="random")if(en_ship1_startR_armor<en_ship1_endR_armor-par.dif_hp)en_ship1_startR_armor+=par.dif_hp;
		}
		/*if(room==rm_edit_enShip1_speedCM){
			if(en_ship1_speed=="random")if(en_ship1_startR_speed<en_ship1_endR_speed-par.dif_speed)en_ship1_startR_speed+=par.dif_speed;
		}
		if(room==rm_edit_enShip1_dmgCM){
			if(en_ship1_dmg=="random")if(en_ship1_startR_dmg<en_ship1_endR_dmg-par.dif_dmg)en_ship1_startR_dmg+=par.dif_dmg;
		}*/
	#endregion
	#region//Death
		if(room==rm_edit_enShip1_pointsCM){
			if(en_ship1_points=="random"){
				if(en_ship1_startR_points<en_ship1_endR_points-par.dif_points)en_ship1_startR_points+=par.dif_points;
			}
		}
	#endregion
	#region//Appearance
		if(room==rm_edit_enShip1_sizeCM){
			if(en_ship1_size=="random")if(en_ship1_startR_size<en_ship1_endR_size-par.dif_size)en_ship1_startR_size+=par.dif_size;
		}
	#endregion
	#region//Bullet
		if(room==rm_edit_enShip1_bt_freqCM){
			if(en_ship1_bt_freq=="random")if(en_ship1_bt_startR_freq<en_ship1_bt_endR_freq-par.dif_freq)en_ship1_bt_startR_freq+=par.dif_freq;
		}
		if(room==rm_edit_enShip1_bt_speedCM){
			if(en_ship1_bt_speed=="random")if(en_ship1_bt_startR_speed<en_ship1_bt_endR_speed-par.dif_speed)en_ship1_bt_startR_speed+=par.dif_speed;
		}
		if(room==rm_edit_enShip1_bt_dmgCM){
			if(en_ship1_bt_dmg=="random")if(en_ship1_bt_startR_dmg<en_ship1_bt_endR_dmg-par.dif_dmg)en_ship1_bt_startR_dmg+=par.dif_dmg;
		}
		if(room==rm_edit_enShip1_bt_sizeCM){
			if(en_ship1_bt_size=="random")if(en_ship1_bt_startR_size<en_ship1_bt_endR_size-par.dif_size)en_ship1_bt_startR_size+=par.dif_size;
		}
	#endregion
#endregion
#region//HLaser
	#region//Base
	if(room==rm_edit_HLaser_dmgCM){
		if(hlaser_dmg=="random"){
			if(hlaser_startR_dmg<hlaser_endR_dmg-par.dif_dmg)hlaser_startR_dmg+=par.dif_dmg;
		}
	}
	if(room==rm_edit_HLaser_dmgintrvCM){
		if(hlaser_dmgintrv=="random"){
			if(hlaser_startR_dmgintrv<hlaser_endR_dmgintrv-par.dif_freq)hlaser_startR_dmgintrv+=par.dif_freq;
		}
	}
	if(room==rm_edit_HLaser_alarmCM){
		if(hlaser_alarm=="random"){
			if(hlaser_startR_alarm<hlaser_endR_alarm-par.dif_freq)hlaser_startR_alarm+=par.dif_freq;
		}
	}
	if(room==rm_edit_HLaser_durCM){
		if(hlaser_dur=="random"){
			if(hlaser_startR_dur<hlaser_endR_dur-par.dif_freq)hlaser_startR_dur+=par.dif_freq;
		}
	}
	if(room==rm_edit_HLaser_chargeCM){
		if(hlaser_charge=="random"){
			if(hlaser_startR_charge<hlaser_endR_charge-par.dif_freq)hlaser_startR_charge+=par.dif_freq;
		}
	}
	#endregion
#endregion
}