/// @description Add to spleech_place_constant
with(obj_custommode_cntrl){
	if(room==rm_editSPLeech_spawnCM){
		if(spleech_place=="constant"){
			if(spleech_place_constant<202)spleech_place_constant+=16;
		}
		if(spleech_place=="mirrored"){
			if(spleech_place_constant<112)spleech_place_constant+=16;
		}
	}
	if(room==rm_editHLaser_spawnCM){
		if(hlaser_place=="constant"){
			if(hlaser_place_constant<202)hlaser_place_constant+=16;
		}
		if(hlaser_place=="mirrored"){
			if(hlaser_place_constant<112)hlaser_place_constant+=16;
		}
	}
}