/// @description Contract from
with(obj_custommode_cntrl){
var par=obj_smodeParent;
#region//Comet
	#region//Base
	if(room==rm_editcomet_armorCM){
		if(comet_armor=="constant"){
			if(comet_constant_armor>par.min_hp)comet_constant_armor-=par.dif_hp;
		}
	}
	if(room==rm_editcomet_speedCM){
		if(comet_speed=="constant"){
			if(comet_constant_speed>par.min_speed)comet_constant_speed-=par.dif_speed;
		}
	}
	if(room==rm_editcomet_dmgCM){
		if(comet_dmg=="constant"){
			if(comet_constant_dmg>par.min_dmg)comet_constant_dmg-=par.dif_dmg;
		}
	}
	#endregion
	#region//Death
	if(room==rm_editcomet_pointsCM){
		if(comet_points=="constant"){
			if(comet_constant_points>par.min_points)comet_constant_points-=par.dif_points;
		}
	}
	#endregion
	#region//Appearance
	if(room==rm_editcomet_sizeCM){
		if(comet_size=="constant"){
			if(comet_constant_size>par.min_size)comet_constant_size-=par.dif_size;
		}
	}
	#endregion
#endregion
#region//Bat
	#region//Base
	if(room==rm_editbat_armorCM){
		if(bat_armor=="constant"){
			if(bat_constant_armor>par.min_hp)bat_constant_armor-=par.dif_hp;
		}
	}
	if(room==rm_editbat_speedCM){
		if(bat_speed=="constant"){
			if(bat_constant_speed>par.min_speed)bat_constant_speed-=par.dif_speed;
		}
	}
	if(room==rm_editbat_dmgCM){
		if(bat_dmg=="constant"){
			if(bat_constant_dmg>par.min_dmg)bat_constant_dmg-=par.dif_dmg;
		}
	}
	#endregion
	#region//Death
	if(room==rm_editbat_pointsCM){
		if(bat_points=="constant"){
			if(bat_constant_points>par.min_points)bat_constant_points-=par.dif_points;
		}
	}
	#endregion
	#region//Appearance
	if(room==rm_editbat_sizeCM){
		if(bat_size=="constant"){
			if(bat_constant_size>par.min_size)bat_constant_size-=par.dif_size;
		}
	}
	#endregion
	#region//Bullet
	if(room==rm_editbat_bt_freqCM){
		if(bat_bt_freq=="constant"){
			if(bat_bt_constant_freq>par.min_freq)bat_bt_constant_freq-=par.dif_freq;
		}
	}
	if(room==rm_editbat_bt_speedCM){
		if(bat_bt_speed=="constant"){
			if(bat_bt_constant_speed>par.min_speed)bat_bt_constant_speed-=par.dif_speed;
		}
	}
	if(room==rm_editbat_bt_dmgCM){
		if(bat_bt_dmg=="constant"){
			if(bat_bt_constant_dmg>par.min_dmg)bat_bt_constant_dmg-=par.dif_dmg;
		}
	}
	if(room==rm_editbat_bt_sizeCM){
		if(bat_bt_size=="constant"){
			if(bat_bt_constant_size>par.min_size)bat_bt_constant_size-=par.dif_size;
		}
	}
	#endregion
#endregion
#region//Enemy Ship1
	#region//Base
	if(room==rm_edit_enShip1_armorCM){
		if(en_ship1_armor=="constant"){
			if(en_ship1_constant_armor>par.min_hp)en_ship1_constant_armor-=par.dif_hp;
		}
	}
	/*if(room==rm_edit_enShip1_speedCM){
		if(en_ship1_speed=="constant"){
			if(en_ship1_constant_speed>par.min_speed)en_ship1_constant_speed-=par.dif_speed;
		}
	}
	if(room==rm_edit_enShip1_dmgCM){
		if(en_ship1_dmg=="constant"){
			if(en_ship1_constant_dmg>par.min_dmg)en_ship1_constant_dmg-=par.dif_dmg;
		}
	}*/
	#endregion
	#region//Death
	if(room==rm_edit_enShip1_pointsCM){
		if(en_ship1_points=="constant"){
			if(en_ship1_constant_points>par.min_points)en_ship1_constant_points-=par.dif_points;
		}
	}
	#endregion
	#region//Appearance
	if(room==rm_edit_enShip1_sizeCM){
		if(en_ship1_size=="constant"){
			if(en_ship1_constant_size>par.min_size)en_ship1_constant_size-=par.dif_size;
		}
	}
	#endregion
	#region//Bullet
	if(room==rm_edit_enShip1_bt_freqCM){
		if(en_ship1_bt_freq=="constant"){
			if(en_ship1_bt_constant_freq>par.min_freq)en_ship1_bt_constant_freq-=par.dif_freq;
		}
	}
	if(room==rm_edit_enShip1_bt_speedCM){
		if(en_ship1_bt_speed=="constant"){
			if(en_ship1_bt_constant_speed>par.min_speed)en_ship1_bt_constant_speed-=par.dif_speed;
		}
	}
	if(room==rm_edit_enShip1_bt_dmgCM){
		if(en_ship1_bt_dmg=="constant"){
			if(en_ship1_bt_constant_dmg>par.min_dmg)en_ship1_bt_constant_dmg-=par.dif_dmg;
		}
	}
	if(room==rm_edit_enShip1_bt_sizeCM){
		if(en_ship1_bt_size=="constant"){
			if(en_ship1_bt_constant_size>par.min_size)en_ship1_bt_constant_size-=par.dif_size;
		}
	}
	if(room==rm_edit_enShip1_bt_sepparCM){
		if(en_ship1_bt_seppar>par.min_seppar)en_ship1_bt_seppar-=par.dif_seppar;
	}
	#endregion
#endregion
#region//HLaser
	#region//Base
	if(room==rm_edit_HLaser_dmgCM){
		if(hlaser_dmg=="constant"){
			if(hlaser_constant_dmg>par.min_dmg)hlaser_constant_dmg-=par.dif_dmg;
		}
	}
	if(room==rm_edit_HLaser_dmgintrvCM){
		if(hlaser_dmgintrv=="constant"){
			if(hlaser_constant_dmgintrv>par.min_freq)hlaser_constant_dmgintrv-=par.dif_freq;
		}
	}
	if(room==rm_edit_HLaser_alarmCM){
		if(hlaser_alarm=="constant"){
			if(hlaser_constant_alarm>par.min_freq)hlaser_constant_alarm-=par.dif_freq;
		}
	}
	if(room==rm_edit_HLaser_durCM){
		if(hlaser_dur=="constant"){
			if(hlaser_constant_dur>par.min_freq)hlaser_constant_dur-=par.dif_freq;
		}
	}
	if(room==rm_edit_HLaser_chargeCM){
		if(hlaser_charge=="constant"){
			if(hlaser_constant_charge>par.min_freq)hlaser_constant_charge-=par.dif_freq;
		}
	}
	#endregion
#endregion
}