/// @description Contract from
with(obj_custommode_cntrl){
var par=obj_smodeParent;
#region//Comet
	#region//Base
	if(room==rm_editcomet_armorCM){
		if(comet_armor=="size"){
			if(comet_sizeB_armor>par.min_hp)comet_sizeB_armor-=par.dif_hp;
		}
	}
	if(room==rm_editcomet_speedCM){
		if(comet_speed=="size"){
			if(comet_sizeB_speed>par.min_speed)comet_sizeB_speed-=par.dif_speed;
		}
	}
	if(room==rm_editcomet_dmgCM){
		if(comet_dmg=="size"){
			if(comet_sizeB_dmg>par.min_dmg)comet_sizeB_dmg-=par.dif_dmg;
		}
	}
	#endregion
	#region//Death
	if(room==rm_editcomet_pointsCM){
		if(comet_points=="size"){
			if(comet_sizeB_points>par.min_points)comet_sizeB_points-=par.dif_points;
		}
	}
	#endregion
	#region//Appearance
	
	#endregion
#endregion
#region//Bat
	#region//Base
	if(room==rm_editbat_armorCM){
		if(bat_armor=="size"){
			if(bat_sizeB_armor>par.min_hp)bat_sizeB_armor-=par.dif_hp;
		}
	}
	if(room==rm_editbat_speedCM){
		if(bat_speed=="size"){
			if(bat_sizeB_speed>par.min_speed)bat_sizeB_speed-=par.dif_speed;
		}
	}
	if(room==rm_editbat_dmgCM){
		if(bat_dmg=="size"){
			if(bat_sizeB_dmg>par.min_dmg)bat_sizeB_dmg-=par.dif_dmg;
		}
	}
	#endregion
	#region//Death
	if(room==rm_editbat_pointsCM){
		if(bat_points=="size"){
			if(bat_sizeB_points>par.min_points)bat_sizeB_points-=par.dif_points;
		}
	}
	#endregion
	#region//Appearance
	
	#endregion
	#region//Bullet
	if(room==rm_editbat_bt_freqCM){
		if(bat_bt_freq=="size"){
			if(bat_bt_sizeB_freq>par.min_freq)bat_bt_sizeB_freq-=par.dif_freq;
		}
	}
	if(room==rm_editbat_bt_speedCM){
		if(bat_bt_speed=="size"){
			if(bat_bt_sizeB_speed>par.min_speed)bat_bt_sizeB_speed-=par.dif_speed;
		}
	}
	if(room==rm_editbat_bt_dmgCM){
		if(bat_bt_dmg=="size"){
			if(bat_bt_sizeB_dmg>par.min_dmg)bat_bt_sizeB_dmg-=par.dif_dmg;
		}
	}
	/*if(room==rm_editbat_bt_sizeCM){
		if(bat_bt_size=="size"){
			if(bat_bt_sizeB_size>par.min_size)bat_bt_sizeB_size-=par.dif_size;
		}
	}*/
	#endregion
#endregion
#region//Enemy Ship1
	#region//Base
	if(room==rm_edit_enShip1_armorCM){
		if(en_ship1_armor=="size"){
			if(en_ship1_sizeB_armor>par.min_hp)en_ship1_sizeB_armor-=par.dif_hp;
		}
	}
	/*if(room==rm_edit_enShip1_speedCM){
		if(en_ship1_speed=="size"){
			if(en_ship1_sizeB_speed>par.min_speed)en_ship1_sizeB_speed-=par.dif_speed;
		}
	}
	if(room==rm_edit_enShip1_dmgCM){
		if(en_ship1_dmg=="size"){
			if(en_ship1_sizeB_dmg>par.min_dmg)en_ship1_sizeB_dmg-=par.dif_dmg;
		}
	}*/
	#endregion
	#region//Death
	if(room==rm_edit_enShip1_pointsCM){
		if(en_ship1_points=="size"){
			if(en_ship1_sizeB_points>par.min_points)en_ship1_sizeB_points-=par.dif_points;
		}
	}
	#endregion
	#region//Appearance
	
	#endregion
	#region//Bullet
	if(room==rm_edit_enShip1_bt_freqCM){
		if(en_ship1_bt_freq=="size"){
			if(en_ship1_bt_sizeB_freq>par.min_freq)en_ship1_bt_sizeB_freq-=par.dif_freq;
		}
	}
	if(room==rm_edit_enShip1_bt_speedCM){
		if(en_ship1_bt_speed=="size"){
			if(en_ship1_bt_sizeB_speed>par.min_speed)en_ship1_bt_sizeB_speed-=par.dif_speed;
		}
	}
	if(room==rm_edit_enShip1_bt_dmgCM){
		if(en_ship1_bt_dmg=="size"){
			if(en_ship1_bt_sizeB_dmg>par.min_dmg)en_ship1_bt_sizeB_dmg-=par.dif_dmg;
		}
	}
	/*if(room==rm_edit_enShip1_bt_sizeCM){
		if(en_ship1_bt_size=="size"){
			if(en_ship1_bt_sizeB_size>par.min_size)en_ship1_bt_sizeB_size-=par.dif_size;
		}
	}*/
	#endregion
#endregion
}